sonar.projectKey=JulianiusM_Surveyor_5d91eae7-0c34-44b1-800d-40728c1a622c
sonar.projectName=Surveyor
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info,coverage/client/lcov.info
sonar.coverageReportPaths=coverage/cobertura-coverage.xml,coverage/client/cobertura-coverage.xml
sonar.exclusions=node_modules/**,dist/**,**/*.spec.ts