/**
 * Test data for activity-recommendations.ts
 */

export const activityRecommendationsData = {
    initialization: {
        valid: {
            planId: 'plan123',
            panelId: 'recommendationPanel',
        },
        missing: {
            planId: '',
        },
    },

    recommendations: {
        empty: [],
        single: [
            {
                id: 'rec1',
                slot: {
                    id: 'slot1',
                    title: 'Morning Shift',
                    day: '2024-12-15',
                    startTime: '08:00:00',
                    endTime: '12:00:00',
                },
                user: {id: 1, username: 'john_doe'},
                guest: null,
                status: 'PENDING',
            },
        ],
        multiple: [
            {
                id: 'rec1',
                slot: {id: 'slot1', title: 'Morning Shift', day: '2024-12-15'},
                user: {id: 1, username: 'john_doe'},
                guest: null,
                status: 'PENDING',
            },
            {
                id: 'rec2',
                slot: {id: 'slot2', title: 'Afternoon Shift', day: '2024-12-15'},
                user: null,
                guest: {id: 1, username: 'guest_user'},
                status: 'APPROVED',
            },
            {
                id: 'rec3',
                slot: {id: 'slot3', title: 'Evening Shift', day: '2024-12-16'},
                user: {id: 2, username: 'jane_smith'},
                guest: null,
                status: 'REJECTED',
            },
            {
                id: 'rec4',
                slot: {id: 'slot4', title: 'Night Shift', day: '2024-12-16'},
                user: {id: 3, username: 'bob_jones'},
                guest: null,
                status: 'APPLIED',
            },
        ],
    },

    warnings: {
        empty: [],
        single: [
            {
                recommendation: {
                    slotId: 'slot1',
                    userId: 1,
                    guestId: null,
                },
                warnings: [
                    {type: 'OVERLAP', slotId: 'slot2', description: 'Time overlap'},
                ],
            },
        ],
        multiple: [
            {
                recommendation: {slotId: 'slot1', userId: 1, guestId: null},
                warnings: [
                    {type: 'OVERLAP', slotId: 'slot2'},
                    {type: 'CAPACITY', slotId: 'slot1'},
                ],
            },
        ],
    },

    participants: [
        {
            key: 'user:1',
            label: 'John Doe',
            userId: 1,
            guestId: null,
            arrivalDate: '2024-12-14',
            departureDate: '2024-12-17',
        },
        {
            key: 'guest:1',
            label: 'Guest User',
            userId: null,
            guestId: 1,
            arrivalDate: null,
            departureDate: null,
        },
    ],

    slots: [
        {
            id: 'slot1',
            title: 'Morning Shift',
            day: '2024-12-15',
            startTime: '08:00:00',
            endTime: '12:00:00',
        },
        {
            id: 'slot2',
            title: 'Afternoon Shift',
            day: '2024-12-15',
            startTime: '12:00:00',
            endTime: '16:00:00',
        },
    ],

    apiResponses: {
        loadSuccess: {
            status: 'success',
            data: {
                recommendations: [],
                warnings: [],
                slots: [],
                participants: [],
                autoGenerated: false,
            },
        },
        loadSuccessAutoGenerated: {
            status: 'success',
            data: {
                recommendations: [],
                warnings: [],
                slots: [],
                participants: [],
                autoGenerated: true,
            },
        },
        loadError: {
            status: 'error',
            message: 'Failed to load recommendations',
        },
        saveSuccess: {
            status: 'success',
            message: 'Recommendations saved',
        },
        saveError: {
            status: 'error',
            message: 'Failed to save recommendations',
        },
        autoSuccess: {
            status: 'success',
            message: 'Recommendations generated',
        },
        applySuccess: {
            status: 'success',
            message: 'Recommendations applied successfully',
            warnings: [],
        },
    },

    summaryStats: {
        empty: {
            PENDING: 0,
            APPROVED: 0,
            REJECTED: 0,
            APPLIED: 0,
        },
        mixed: {
            PENDING: 2,
            APPROVED: 3,
            REJECTED: 1,
            APPLIED: 1,
        },
    },
};
