import {MigrationInterface, QueryRunner} from "typeorm";

export class Baseline1752829814405 implements MigrationInterface {
    name = 'Baseline1752829814405'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`activity_plans\` DROP FOREIGN KEY \`activity_plans_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`activity_slots\` DROP FOREIGN KEY \`activity_slots_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`activity_slot_role\` DROP FOREIGN KEY \`activity_slot_role_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`activity_slot_role\` DROP FOREIGN KEY \`activity_slot_role_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`activity_assignment_roles\` DROP FOREIGN KEY \`activity_assignment_roles_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`activity_assignment_roles\` DROP FOREIGN KEY \`activity_assignment_roles_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`drivers_lists\` DROP FOREIGN KEY \`drivers_lists_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`drivers_items\` DROP FOREIGN KEY \`drivers_items_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`drivers_items\` DROP FOREIGN KEY \`drivers_items_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`drivers_items\` DROP FOREIGN KEY \`drivers_items_ibfk_3\``);
        await queryRunner.query(`ALTER TABLE \`drivers_assignments\` DROP FOREIGN KEY \`drivers_assignments_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`drivers_assignments\` DROP FOREIGN KEY \`drivers_assignments_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`drivers_assignments\` DROP FOREIGN KEY \`drivers_assignments_ibfk_3\``);
        await queryRunner.query(`ALTER TABLE \`drivers_assignments\` DROP FOREIGN KEY \`drivers_assignments_ibfk_4\``);
        await queryRunner.query(`ALTER TABLE \`guest_links\` DROP FOREIGN KEY \`fk_guest_links_guest\``);
        await queryRunner.query(`ALTER TABLE \`packing_lists\` DROP FOREIGN KEY \`fk_packing_list_user\``);
        await queryRunner.query(`ALTER TABLE \`packing_items\` DROP FOREIGN KEY \`fk_packing_items_list\``);
        await queryRunner.query(`ALTER TABLE \`packing_assignments\` DROP FOREIGN KEY \`fk_packing_ass_guest\``);
        await queryRunner.query(`ALTER TABLE \`packing_assignments\` DROP FOREIGN KEY \`fk_packing_ass_item\``);
        await queryRunner.query(`ALTER TABLE \`packing_assignments\` DROP FOREIGN KEY \`fk_packing_ass_list\``);
        await queryRunner.query(`ALTER TABLE \`surveys\` DROP FOREIGN KEY \`surveys_owner_id_user_id_fk\``);
        await queryRunner.query(`ALTER TABLE \`survey_combinations\` DROP FOREIGN KEY \`combinations_surveys_id_fk\``);
        await queryRunner.query(`ALTER TABLE \`survey_responses\` DROP FOREIGN KEY \`responses_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`survey_responses\` DROP FOREIGN KEY \`responses_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`survey_responses\` DROP FOREIGN KEY \`responses_ibfk_3\``);
        await queryRunner.query(`ALTER TABLE \`survey_responses\` DROP FOREIGN KEY \`responses_surveys_id_fk\``);
        await queryRunner.query(`ALTER TABLE \`activity_assignments\` DROP FOREIGN KEY \`activity_assignments_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`activity_assignments\` DROP FOREIGN KEY \`activity_assignments_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`activity_assignments\` DROP FOREIGN KEY \`activity_assignments_ibfk_3\``);
        await queryRunner.query(`ALTER TABLE \`activity_assignments\` DROP FOREIGN KEY \`activity_assignments_ibfk_4\``);
        await queryRunner.query(`ALTER TABLE \`activity_plans\` CHANGE \`updated_at\` \`updated_at\` timestamp NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`activity_slots\` CHANGE \`updated_at\` \`updated_at\` timestamp NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`activity_assignment_roles\` CHANGE \`updated_at\` \`updated_at\` timestamp NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`drivers_lists\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`drivers_lists\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`drivers_lists\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`drivers_lists\` CHANGE \`updated_at\` \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`DROP INDEX \`list_id\` ON \`drivers_items\``);
        await queryRunner.query(`ALTER TABLE \`drivers_items\` DROP COLUMN \`list_id\``);
        await queryRunner.query(`ALTER TABLE \`drivers_items\` ADD \`list_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`drivers_items\` CHANGE \`updated_at\` \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`DROP INDEX \`list_id\` ON \`drivers_assignments\``);
        await queryRunner.query(`ALTER TABLE \`drivers_assignments\` DROP COLUMN \`list_id\``);
        await queryRunner.query(`ALTER TABLE \`drivers_assignments\` ADD \`list_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`drivers_assignments\` CHANGE \`updated_at\` \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`packing_lists\` CHANGE \`updated_at\` \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`packing_items\` CHANGE \`updated_at\` \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`packing_assignments\` CHANGE \`updated_at\` \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`surveys\` CHANGE \`updated_at\` \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`survey_combinations\` CHANGE \`updated_at\` \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`survey_responses\` CHANGE \`updated_at\` \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`guests\` CHANGE \`updated_at\` \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`activity_assignments\` CHANGE \`updatedAt\` \`updatedAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`updated_at\` \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_648e3f5447f725579d7d4ffdfb\` ON \`roles\` (\`name\`)`);
        await queryRunner.query(`CREATE INDEX \`list_id\` ON \`drivers_items\` (\`list_id\`)`);
        await queryRunner.query(`CREATE INDEX \`list_id\` ON \`drivers_assignments\` (\`list_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_a7bd19b2b50ea07b5120d0616e\` ON \`guest_links\` (\`token\`)`);
        await queryRunner.query(`CREATE INDEX \`fk_packing_list_user\` ON \`packing_lists\` (\`owner_id\`)`);
        await queryRunner.query(`CREATE INDEX \`fk_packing_items_list\` ON \`packing_items\` (\`list_id\`)`);
        await queryRunner.query(`CREATE INDEX \`fk_packing_ass_list\` ON \`packing_assignments\` (\`list_id\`)`);
        await queryRunner.query(`CREATE INDEX \`fk_packing_ass_guest\` ON \`packing_assignments\` (\`guest_id\`)`);
        await queryRunner.query(`CREATE INDEX \`surveys_owner_id_user_id_fk\` ON \`surveys\` (\`owner_id\`)`);
        await queryRunner.query(`CREATE INDEX \`combinations_surveys_id_fk\` ON \`survey_combinations\` (\`survey_id\`)`);
        await queryRunner.query(`CREATE INDEX \`responses_surveys_id_fk\` ON \`survey_responses\` (\`survey_id\`)`);
        await queryRunner.query(`CREATE INDEX \`responses_ibfk_3\` ON \`survey_responses\` (\`combination_id\`)`);
        await queryRunner.query(`CREATE INDEX \`responses_ibfk_2\` ON \`survey_responses\` (\`guest_id\`)`);
        await queryRunner.query(`CREATE INDEX \`responses_ibfk_1\` ON \`survey_responses\` (\`user_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_fe0bb3f6520ee0469504521e71\` ON \`users\` (\`username\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\` (\`email\`)`);
        await queryRunner.query(`ALTER TABLE \`activity_plans\` ADD CONSTRAINT \`FK_d4636d5c694bae3fd270f7c266f\` FOREIGN KEY (\`owner_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`activity_slots\` ADD CONSTRAINT \`FK_46f987c26b60e3396f22d53735e\` FOREIGN KEY (\`plan_id\`) REFERENCES \`activity_plans\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`activity_slot_role\` ADD CONSTRAINT \`FK_0302a1df8a7c1ea8bc3cd8f98f0\` FOREIGN KEY (\`slot_id\`) REFERENCES \`activity_slots\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`activity_slot_role\` ADD CONSTRAINT \`FK_58f6f2ef62b056799257cfffb03\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`activity_assignment_roles\` ADD CONSTRAINT \`FK_74b6651e64642f492f59c76c290\` FOREIGN KEY (\`assignment_id\`) REFERENCES \`activity_assignments\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`activity_assignment_roles\` ADD CONSTRAINT \`FK_0c516280b2238a94628e1ae3076\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`drivers_lists\` ADD CONSTRAINT \`FK_f124e3b4cbdb69f28f796e1cc99\` FOREIGN KEY (\`owner_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`drivers_items\` ADD CONSTRAINT \`FK_ee27f34d81abc82359683f84e38\` FOREIGN KEY (\`list_id\`) REFERENCES \`drivers_lists\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`drivers_items\` ADD CONSTRAINT \`FK_357c0fbec24aac87ee423ba5168\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`drivers_items\` ADD CONSTRAINT \`FK_ccd3f1ec65169179b395e5ba903\` FOREIGN KEY (\`guest_id\`) REFERENCES \`guests\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`drivers_assignments\` ADD CONSTRAINT \`FK_797f953903af106421d5f2cada2\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`drivers_assignments\` ADD CONSTRAINT \`FK_dc269892d22b330ef2c60aead83\` FOREIGN KEY (\`guest_id\`) REFERENCES \`guests\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`drivers_assignments\` ADD CONSTRAINT \`FK_b2fa5cb20b56122626e22bce5ee\` FOREIGN KEY (\`item_id\`) REFERENCES \`drivers_items\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`drivers_assignments\` ADD CONSTRAINT \`FK_33c32c9f3dbd2e9eaa63b7f08bf\` FOREIGN KEY (\`list_id\`) REFERENCES \`drivers_lists\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`guest_links\` ADD CONSTRAINT \`FK_2e0c589078726b792e524056f38\` FOREIGN KEY (\`guest_id\`) REFERENCES \`guests\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`packing_lists\` ADD CONSTRAINT \`FK_a801f486411025640abc78bbd91\` FOREIGN KEY (\`owner_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`packing_items\` ADD CONSTRAINT \`FK_6207edc397ed15fcbf1b87b1927\` FOREIGN KEY (\`list_id\`) REFERENCES \`packing_lists\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`packing_assignments\` ADD CONSTRAINT \`FK_c217003837bbf8a7b3a2c1eeb80\` FOREIGN KEY (\`guest_id\`) REFERENCES \`guests\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`packing_assignments\` ADD CONSTRAINT \`FK_8424e042fc819f09baadaf30bb8\` FOREIGN KEY (\`item_id\`) REFERENCES \`packing_items\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`packing_assignments\` ADD CONSTRAINT \`FK_574be0a35d91af3bac4e3f5ee73\` FOREIGN KEY (\`list_id\`) REFERENCES \`packing_lists\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`surveys\` ADD CONSTRAINT \`FK_9532b923178387169ff592c12a9\` FOREIGN KEY (\`owner_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`survey_combinations\` ADD CONSTRAINT \`FK_c0e64c6fe4352a75372af4e98be\` FOREIGN KEY (\`survey_id\`) REFERENCES \`surveys\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`survey_responses\` ADD CONSTRAINT \`FK_15c9124bfeb633545c5de42edb6\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`survey_responses\` ADD CONSTRAINT \`FK_14bcf49cc71d7f857892abbfb0e\` FOREIGN KEY (\`guest_id\`) REFERENCES \`guests\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`survey_responses\` ADD CONSTRAINT \`FK_235dcfd351bc1eb6d12894b7e8f\` FOREIGN KEY (\`combination_id\`) REFERENCES \`survey_combinations\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`survey_responses\` ADD CONSTRAINT \`FK_2b4e3f83ce0b4a0d7617ac0cd44\` FOREIGN KEY (\`survey_id\`) REFERENCES \`surveys\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`activity_assignments\` ADD CONSTRAINT \`FK_aec8db1f4174e3b0f6bfc8fad09\` FOREIGN KEY (\`slot_id\`) REFERENCES \`activity_slots\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`activity_assignments\` ADD CONSTRAINT \`FK_c9be315fed7f07cfc32196eb73d\` FOREIGN KEY (\`plan_id\`) REFERENCES \`activity_plans\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`activity_assignments\` ADD CONSTRAINT \`FK_b56fb307a2d9170d1fd91d53240\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`activity_assignments\` ADD CONSTRAINT \`FK_9e96938fab1057b20f085550ed0\` FOREIGN KEY (\`guest_id\`) REFERENCES \`guests\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`activity_assignments\` DROP FOREIGN KEY \`FK_9e96938fab1057b20f085550ed0\``);
        await queryRunner.query(`ALTER TABLE \`activity_assignments\` DROP FOREIGN KEY \`FK_b56fb307a2d9170d1fd91d53240\``);
        await queryRunner.query(`ALTER TABLE \`activity_assignments\` DROP FOREIGN KEY \`FK_c9be315fed7f07cfc32196eb73d\``);
        await queryRunner.query(`ALTER TABLE \`activity_assignments\` DROP FOREIGN KEY \`FK_aec8db1f4174e3b0f6bfc8fad09\``);
        await queryRunner.query(`ALTER TABLE \`survey_responses\` DROP FOREIGN KEY \`FK_2b4e3f83ce0b4a0d7617ac0cd44\``);
        await queryRunner.query(`ALTER TABLE \`survey_responses\` DROP FOREIGN KEY \`FK_235dcfd351bc1eb6d12894b7e8f\``);
        await queryRunner.query(`ALTER TABLE \`survey_responses\` DROP FOREIGN KEY \`FK_14bcf49cc71d7f857892abbfb0e\``);
        await queryRunner.query(`ALTER TABLE \`survey_responses\` DROP FOREIGN KEY \`FK_15c9124bfeb633545c5de42edb6\``);
        await queryRunner.query(`ALTER TABLE \`survey_combinations\` DROP FOREIGN KEY \`FK_c0e64c6fe4352a75372af4e98be\``);
        await queryRunner.query(`ALTER TABLE \`surveys\` DROP FOREIGN KEY \`FK_9532b923178387169ff592c12a9\``);
        await queryRunner.query(`ALTER TABLE \`packing_assignments\` DROP FOREIGN KEY \`FK_574be0a35d91af3bac4e3f5ee73\``);
        await queryRunner.query(`ALTER TABLE \`packing_assignments\` DROP FOREIGN KEY \`FK_8424e042fc819f09baadaf30bb8\``);
        await queryRunner.query(`ALTER TABLE \`packing_assignments\` DROP FOREIGN KEY \`FK_c217003837bbf8a7b3a2c1eeb80\``);
        await queryRunner.query(`ALTER TABLE \`packing_items\` DROP FOREIGN KEY \`FK_6207edc397ed15fcbf1b87b1927\``);
        await queryRunner.query(`ALTER TABLE \`packing_lists\` DROP FOREIGN KEY \`FK_a801f486411025640abc78bbd91\``);
        await queryRunner.query(`ALTER TABLE \`guest_links\` DROP FOREIGN KEY \`FK_2e0c589078726b792e524056f38\``);
        await queryRunner.query(`ALTER TABLE \`drivers_assignments\` DROP FOREIGN KEY \`FK_33c32c9f3dbd2e9eaa63b7f08bf\``);
        await queryRunner.query(`ALTER TABLE \`drivers_assignments\` DROP FOREIGN KEY \`FK_b2fa5cb20b56122626e22bce5ee\``);
        await queryRunner.query(`ALTER TABLE \`drivers_assignments\` DROP FOREIGN KEY \`FK_dc269892d22b330ef2c60aead83\``);
        await queryRunner.query(`ALTER TABLE \`drivers_assignments\` DROP FOREIGN KEY \`FK_797f953903af106421d5f2cada2\``);
        await queryRunner.query(`ALTER TABLE \`drivers_items\` DROP FOREIGN KEY \`FK_ccd3f1ec65169179b395e5ba903\``);
        await queryRunner.query(`ALTER TABLE \`drivers_items\` DROP FOREIGN KEY \`FK_357c0fbec24aac87ee423ba5168\``);
        await queryRunner.query(`ALTER TABLE \`drivers_items\` DROP FOREIGN KEY \`FK_ee27f34d81abc82359683f84e38\``);
        await queryRunner.query(`ALTER TABLE \`drivers_lists\` DROP FOREIGN KEY \`FK_f124e3b4cbdb69f28f796e1cc99\``);
        await queryRunner.query(`ALTER TABLE \`activity_assignment_roles\` DROP FOREIGN KEY \`FK_0c516280b2238a94628e1ae3076\``);
        await queryRunner.query(`ALTER TABLE \`activity_assignment_roles\` DROP FOREIGN KEY \`FK_74b6651e64642f492f59c76c290\``);
        await queryRunner.query(`ALTER TABLE \`activity_slot_role\` DROP FOREIGN KEY \`FK_58f6f2ef62b056799257cfffb03\``);
        await queryRunner.query(`ALTER TABLE \`activity_slot_role\` DROP FOREIGN KEY \`FK_0302a1df8a7c1ea8bc3cd8f98f0\``);
        await queryRunner.query(`ALTER TABLE \`activity_slots\` DROP FOREIGN KEY \`FK_46f987c26b60e3396f22d53735e\``);
        await queryRunner.query(`ALTER TABLE \`activity_plans\` DROP FOREIGN KEY \`FK_d4636d5c694bae3fd270f7c266f\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_fe0bb3f6520ee0469504521e71\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`responses_ibfk_1\` ON \`survey_responses\``);
        await queryRunner.query(`DROP INDEX \`responses_ibfk_2\` ON \`survey_responses\``);
        await queryRunner.query(`DROP INDEX \`responses_ibfk_3\` ON \`survey_responses\``);
        await queryRunner.query(`DROP INDEX \`responses_surveys_id_fk\` ON \`survey_responses\``);
        await queryRunner.query(`DROP INDEX \`combinations_surveys_id_fk\` ON \`survey_combinations\``);
        await queryRunner.query(`DROP INDEX \`surveys_owner_id_user_id_fk\` ON \`surveys\``);
        await queryRunner.query(`DROP INDEX \`fk_packing_ass_guest\` ON \`packing_assignments\``);
        await queryRunner.query(`DROP INDEX \`fk_packing_ass_list\` ON \`packing_assignments\``);
        await queryRunner.query(`DROP INDEX \`fk_packing_items_list\` ON \`packing_items\``);
        await queryRunner.query(`DROP INDEX \`fk_packing_list_user\` ON \`packing_lists\``);
        await queryRunner.query(`DROP INDEX \`IDX_a7bd19b2b50ea07b5120d0616e\` ON \`guest_links\``);
        await queryRunner.query(`DROP INDEX \`list_id\` ON \`drivers_assignments\``);
        await queryRunner.query(`DROP INDEX \`list_id\` ON \`drivers_items\``);
        await queryRunner.query(`DROP INDEX \`IDX_648e3f5447f725579d7d4ffdfb\` ON \`roles\``);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`updated_at\` \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`activity_assignments\` CHANGE \`updatedAt\` \`updatedAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`guests\` CHANGE \`updated_at\` \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`survey_responses\` CHANGE \`updated_at\` \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`survey_combinations\` CHANGE \`updated_at\` \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`surveys\` CHANGE \`updated_at\` \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`packing_assignments\` CHANGE \`updated_at\` \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`packing_items\` CHANGE \`updated_at\` \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`packing_lists\` CHANGE \`updated_at\` \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`drivers_assignments\` CHANGE \`updated_at\` \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`drivers_assignments\` DROP COLUMN \`list_id\``);
        await queryRunner.query(`ALTER TABLE \`drivers_assignments\` ADD \`list_id\` char(36) NOT NULL`);
        await queryRunner.query(`CREATE INDEX \`list_id\` ON \`drivers_assignments\` (\`list_id\`)`);
        await queryRunner.query(`ALTER TABLE \`drivers_items\` CHANGE \`updated_at\` \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`drivers_items\` DROP COLUMN \`list_id\``);
        await queryRunner.query(`ALTER TABLE \`drivers_items\` ADD \`list_id\` char(36) NOT NULL`);
        await queryRunner.query(`CREATE INDEX \`list_id\` ON \`drivers_items\` (\`list_id\`)`);
        await queryRunner.query(`ALTER TABLE \`drivers_lists\` CHANGE \`updated_at\` \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`drivers_lists\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`drivers_lists\` ADD \`id\` char(36) NOT NULL DEFAULT 'UUID()'`);
        await queryRunner.query(`ALTER TABLE \`drivers_lists\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`activity_assignment_roles\` CHANGE \`updated_at\` \`updated_at\` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`activity_slots\` CHANGE \`updated_at\` \`updated_at\` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`activity_plans\` CHANGE \`updated_at\` \`updated_at\` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`activity_assignments\` ADD CONSTRAINT \`activity_assignments_ibfk_4\` FOREIGN KEY (\`guest_id\`) REFERENCES \`guests\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`activity_assignments\` ADD CONSTRAINT \`activity_assignments_ibfk_3\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`activity_assignments\` ADD CONSTRAINT \`activity_assignments_ibfk_2\` FOREIGN KEY (\`plan_id\`) REFERENCES \`activity_plans\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`activity_assignments\` ADD CONSTRAINT \`activity_assignments_ibfk_1\` FOREIGN KEY (\`slot_id\`) REFERENCES \`activity_slots\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`survey_responses\` ADD CONSTRAINT \`responses_surveys_id_fk\` FOREIGN KEY (\`survey_id\`) REFERENCES \`surveys\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`survey_responses\` ADD CONSTRAINT \`responses_ibfk_3\` FOREIGN KEY (\`combination_id\`) REFERENCES \`survey_combinations\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`survey_responses\` ADD CONSTRAINT \`responses_ibfk_2\` FOREIGN KEY (\`guest_id\`) REFERENCES \`guests\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`survey_responses\` ADD CONSTRAINT \`responses_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`survey_combinations\` ADD CONSTRAINT \`combinations_surveys_id_fk\` FOREIGN KEY (\`survey_id\`) REFERENCES \`surveys\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`surveys\` ADD CONSTRAINT \`surveys_owner_id_user_id_fk\` FOREIGN KEY (\`owner_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`packing_assignments\` ADD CONSTRAINT \`fk_packing_ass_list\` FOREIGN KEY (\`list_id\`) REFERENCES \`packing_lists\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`packing_assignments\` ADD CONSTRAINT \`fk_packing_ass_item\` FOREIGN KEY (\`item_id\`) REFERENCES \`packing_items\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`packing_assignments\` ADD CONSTRAINT \`fk_packing_ass_guest\` FOREIGN KEY (\`guest_id\`) REFERENCES \`guests\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`packing_items\` ADD CONSTRAINT \`fk_packing_items_list\` FOREIGN KEY (\`list_id\`) REFERENCES \`packing_lists\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`packing_lists\` ADD CONSTRAINT \`fk_packing_list_user\` FOREIGN KEY (\`owner_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`guest_links\` ADD CONSTRAINT \`fk_guest_links_guest\` FOREIGN KEY (\`guest_id\`) REFERENCES \`guests\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`drivers_assignments\` ADD CONSTRAINT \`drivers_assignments_ibfk_4\` FOREIGN KEY (\`list_id\`) REFERENCES \`drivers_lists\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`drivers_assignments\` ADD CONSTRAINT \`drivers_assignments_ibfk_3\` FOREIGN KEY (\`item_id\`) REFERENCES \`drivers_items\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`drivers_assignments\` ADD CONSTRAINT \`drivers_assignments_ibfk_2\` FOREIGN KEY (\`guest_id\`) REFERENCES \`guests\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`drivers_assignments\` ADD CONSTRAINT \`drivers_assignments_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`drivers_items\` ADD CONSTRAINT \`drivers_items_ibfk_3\` FOREIGN KEY (\`guest_id\`) REFERENCES \`guests\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`drivers_items\` ADD CONSTRAINT \`drivers_items_ibfk_2\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`drivers_items\` ADD CONSTRAINT \`drivers_items_ibfk_1\` FOREIGN KEY (\`list_id\`) REFERENCES \`drivers_lists\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`drivers_lists\` ADD CONSTRAINT \`drivers_lists_ibfk_1\` FOREIGN KEY (\`owner_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`activity_assignment_roles\` ADD CONSTRAINT \`activity_assignment_roles_ibfk_2\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`activity_assignment_roles\` ADD CONSTRAINT \`activity_assignment_roles_ibfk_1\` FOREIGN KEY (\`assignment_id\`) REFERENCES \`activity_assignments\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`activity_slot_role\` ADD CONSTRAINT \`activity_slot_role_ibfk_2\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`activity_slot_role\` ADD CONSTRAINT \`activity_slot_role_ibfk_1\` FOREIGN KEY (\`slot_id\`) REFERENCES \`activity_slots\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`activity_slots\` ADD CONSTRAINT \`activity_slots_ibfk_1\` FOREIGN KEY (\`plan_id\`) REFERENCES \`activity_plans\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`activity_plans\` ADD CONSTRAINT \`activity_plans_ibfk_1\` FOREIGN KEY (\`owner_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
