import controller from "../../../src/controller/activityController";
import {generatePlanRecommendations} from "../../../src/modules/activity/autoAssignment";

jest.mock("../../../src/modules/database/services/ActivityService", () => ({
    getActivityPlanById: jest.fn(),
    getActivitySlotsFlat: jest.fn(),
    getParticipantAssignmentsWithSlots: jest.fn(),
}));

jest.mock("../../../src/modules/database/services/ActivityRequirementService", () => ({
    getRequirementConfiguration: jest.fn(),
}));

jest.mock("../../../src/modules/database/services/ActivityRecommendationService", () => {
    const actual = jest.requireActual("../../../src/modules/database/services/ActivityRecommendationService");
    return {
        getRecommendations: jest.fn(),
        replaceRecommendations: jest.fn(),
        normalizeRecommendationInput: actual.normalizeRecommendationInput,
    };
});

jest.mock("../../../src/modules/database/services/EventService", () => ({
    getEventParticipants: jest.fn(),
}));

jest.mock("../../../src/modules/activity/autoAssignment", () => ({
    generatePlanRecommendations: jest.fn(),
}));

const activityService = jest.requireMock("../../../src/modules/database/services/ActivityService");
const requirementService = jest.requireMock("../../../src/modules/database/services/ActivityRequirementService");
const recommendationService = jest.requireMock("../../../src/modules/database/services/ActivityRecommendationService");
const eventService = jest.requireMock("../../../src/modules/database/services/EventService");

const mockedGeneratePlanRecommendations = generatePlanRecommendations as jest.Mock;

describe("getRecommendations", () => {
    beforeEach(() => {
        jest.resetAllMocks();
    });

    test("auto-generates recommendations after binding deadline", async () => {
        const pastDeadline = new Date(Date.now() - 10_000);

        activityService.getActivityPlanById.mockResolvedValue({
            id: "plan-1",
            bindingDeadline: pastDeadline,
            assignmentMode: "REQUIRED",
            generalRequiredShifts: 1,
            roundingMode: "ROUND",
            startDate: "2025-01-01",
            endDate: "2025-01-02",
            allowOverfillAfterFull: true,
            event: {id: "event-1"},
        });
        requirementService.getRequirementConfiguration.mockResolvedValue({roleRequirements: [], overrides: []});
        recommendationService.getRecommendations.mockResolvedValueOnce([]);
        recommendationService.getRecommendations.mockResolvedValueOnce([
            {
                id: "rec-1",
                slot: {id: "slot-1", day: "2025-01-02", startTime: null, endTime: null},
                user: {id: 1},
                guest: null,
                status: "PENDING",
            },
        ]);
        activityService.getActivitySlotsFlat.mockResolvedValue([
            {id: "slot-1", day: "2025-01-02", pos: 1, startTime: null, endTime: null},
        ]);
        activityService.getParticipantAssignmentsWithSlots.mockResolvedValue({});
        eventService.getEventParticipants.mockResolvedValue([]);
        mockedGeneratePlanRecommendations.mockResolvedValue([{slotId: "slot-1", userId: 1}]);

        const res = await controller.getRecommendations("plan-1");

        expect(mockedGeneratePlanRecommendations).toHaveBeenCalledWith("plan-1");
        expect(recommendationService.replaceRecommendations).toHaveBeenCalledWith("plan-1", [{slotId: "slot-1", userId: 1}]);
        expect(res.autoGenerated).toBe(true);
        expect(res.recommendations).toHaveLength(1);
    });

    test("does not auto-generate before the deadline", async () => {
        const futureDeadline = new Date(Date.now() + 60_000);

        activityService.getActivityPlanById.mockResolvedValue({
            id: "plan-2",
            bindingDeadline: futureDeadline,
            startDate: "2025-01-01",
            endDate: "2025-01-02",
            allowOverfillAfterFull: true,
        });
        requirementService.getRequirementConfiguration.mockResolvedValue({roleRequirements: [], overrides: []});
        recommendationService.getRecommendations.mockResolvedValue([]);
        activityService.getActivitySlotsFlat.mockResolvedValue([]);
        activityService.getParticipantAssignmentsWithSlots.mockResolvedValue({});
        eventService.getEventParticipants.mockResolvedValue([]);

        const res = await controller.getRecommendations("plan-2");

        expect(mockedGeneratePlanRecommendations).not.toHaveBeenCalled();
        expect(recommendationService.replaceRecommendations).not.toHaveBeenCalled();
        expect(res.autoGenerated).toBe(false);
    });
});
